# Generated by Django 3.1.3 on 2020-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='icon.png', null=True, upload_to=''),
        ),
    ]
